name: Talkvee
description: Messaging app for teaching and testing children on internet safety.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.1+1
  flutter_local_notifications: ^0.5.2
  http: ^0.12.0+1
  scoped_model: ^1.0.1
  path_provider: ^0.4.1
  objectdb: ^1.0.5
  json_annotation: ^2.0.0
  local_auth: ^0.3.1
  dynamic_theme: ^1.0.1
  pinput: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true